### ISSUE TITLE
Website errors

### ISSUE THREAD

**Issue by onigumo1990** [AlphaReign/www-php#1]
When I try to access the website, it just simply states, "Doing some maintenance" and when I dug through the files I noticed it only gets to that if it errors out in middleware/counts.php, but wasn't displaying the errors. When I tell it to echo the errors, this is the output I get:

```
Elasticsearch\Common\Exceptions\Missing404Exception: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"torrents","index_uuid":"_na_","index":"torrents"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"torrents","index_uuid":"_na_","index":"torrents"},"status":404} in /var/www/html/alphareign/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:602 Stack trace: #0 /var/www/html/alphareign/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(273): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array) #1 /var/www/html/alphareign/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #2 /var/www/html/alphareign/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #3 /var/www/html/alphareign/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #4 /var/www/html/alphareign/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(294): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure)) #5 /var/www/html/alphareign/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(171): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array) #6 /var/www/html/alphareign/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(100): Elasticsearch\Connections\Connection->performRequest('GET', '/torrents/hash/...', Array, NULL, Array, Object(Elasticsearch\Transport)) #7 /var/www/html/alphareign/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1502): Elasticsearch\Transport->performRequest('GET', '/torrents/hash/...', Array, NULL, Array) #8 /var/www/html/alphareign/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(352): Elasticsearch\Client->performRequest(Object(Elasticsearch\Endpoints\Count)) #9 /var/www/html/alphareign/middleware/counts.php(12): Elasticsearch\Client->count(Array) #10 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #11 /var/www/html/alphareign/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array) #12 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #13 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #14 /var/www/html/alphareign/middleware/es.php(11): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #15 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #16 /var/www/html/alphareign/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array) #17 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #18 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #19 /var/www/html/alphareign/middleware/auth.php(65): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #20 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #21 /var/www/html/alphareign/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array) #22 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #23 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #24 /var/www/html/alphareign/middleware/view.php(60): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #25 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #26 /var/www/html/alphareign/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array) #27 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #28 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #29 /var/www/html/alphareign/middleware/params.php(9): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #30 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #31 /var/www/html/alphareign/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array) #32 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #33 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #34 /var/www/html/alphareign/middleware/cookies.php(8): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #35 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #36 /var/www/html/alphareign/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array) #37 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #38 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #39 /var/www/html/alphareign/vendor/slim/csrf/src/Guard.php(162): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #40 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #41 /var/www/html/alphareign/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Slim\Csrf\Guard), Array) #42 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #43 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #44 /var/www/html/alphareign/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #45 /var/www/html/alphareign/vendor/slim/slim/Slim/App.php(332): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #46 /var/www/html/alphareign/vendor/slim/slim/Slim/App.php(293): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #47 /var/www/html/alphareign/index.php(157): Slim\App->run() #48 {main}
Doing some maintenance
```

I'm sorry for bothering you on probably another simple issue. I have been looking at this for a while though. I installed ElasticSearch 5.0.0 and ran npm install and also composer install. ElasticSearch is running as well.

**Comment by Raxvis** [comment]
Looks like the index doesn't exist in elastic search.  You can comment that out for now. It isn't required for the site. 

Have you had any torrents added?

**Comment by onigumo1990** [comment]
It looks like since I closed that last issue I've had 12 torrents that have logged as "add"

**Comment by Raxvis** [comment]
Can you access one of those torrents that was added?  Should be http://127.0.0.1:9200/torrents/index/{infohash}

**Comment by Raxvis** [comment]
Sorry. That should be http://127.0.0.1:9200/torrents/hash/{infohash}

**Comment by onigumo1990** [comment]
I don't know if I should be able to open that in the webbrowser, my server is a separate machine but when I run curl -X GET 'http://localhost:9200/torrents/hash/0e02dc422816fc354e089cf2ec42e9d137597a2e', the result was `{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"torrents","index_uuid":"_na_","index":"torrents"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"torrents","index_uuid":"_na_","index":"torrents"},"status":404}`

**Comment by Raxvis** [comment]
Ah. That means the torrents aren't getting added for some reason. 

Can you clear your logs for you add.js and let it run tonight and paste them here tomorrow?

**Comment by onigumo1990** [comment]
Do you mean the error log or both logs?

**Comment by Raxvis** [comment]
Both logs. If it's not erroring, I would like to see the output.

**Comment by onigumo1990** [comment]
I can tell you it currently has no errors, but I'll let it run for 12 hours and post.

**Comment by Raxvis** [comment]
Okay. Thanks!

**Comment by onigumo1990** [comment]
Alright, here are both logs for add.js

add-error-0.log is blank

add-out-0.log:
```
UDP Server listening on 0.0.0.0:6881
Added: 07ba9385c16765a264c2a5b2f443375baab64287 | Fawlty.Towers.1975.Complete.Seasons.DVBRip.XviD.BGAUDIO-RRGroup
Added: 31a978f96ecda9a225632f5adac12e4cc2be2067 | The.Shallows.2016.BDRip.1.46Gb.Dub.MegaPeer.avi
Added: 61c6b2ab7126dd0b595fca6e715a0904c107c28b | 30c3-5593-en-Hacking_the_Czech_Parliament_via_SMS_h264-iprod.mp4
Added: 07ba9385c16765a264c2a5b2f443375baab64287 | Fawlty.Towers.1975.Complete.Seasons.DVBRip.XviD.BGAUDIO-RRGroup
Added: d3234c8d458b83637906040bb9a751aa789acd7d | Jonathan.Strange.And.Mr.Norrell.Season.1.HDTV.x264-Scene[SexyTv]
Added: 16e2a6515516225a16b26e601b36cabc2ce35a67 | Otkradnat.jivot.S02E38.DVBRip.x264-SLSS
Added: 073217df190de2e0a2cba5b19669df226f0494bc | Ice.Age.Collision.Course.2016.BDRip.XviD.AC3.BGAUDiO-SLSS
Added: e8fd85c5f9ec9ac6934566242e45e902b82b1350 | Лавлок - Гея_ Новый взгляд на жизнь на Земле (2015)
Added: 1e471e464a80bb456d391713b93ccb46c0f11eff | 3 Doors Down - Us and the Night (Deluxe Edition) (2016)
Added: 07ba9385c16765a264c2a5b2f443375baab64287 | Fawlty.Towers.1975.Complete.Seasons.DVBRip.XviD.BGAUDIO-RRGroup
Added: e8fd85c5f9ec9ac6934566242e45e902b82b1350 | Лавлок - Гея_ Новый взгляд на жизнь на Земле (2015)
Added: e8fd85c5f9ec9ac6934566242e45e902b82b1350 | Лавлок - Гея_ Новый взгляд на жизнь на Земле (2015)
Added: 16e2a6515516225a16b26e601b36cabc2ce35a67 | Otkradnat.jivot.S02E38.DVBRip.x264-SLSS
Added: 07ba9385c16765a264c2a5b2f443375baab64287 | Fawlty.Towers.1975.Complete.Seasons.DVBRip.XviD.BGAUDIO-RRGroup
Added: 34eb25f1d6aea212474e75c5d1498bc7f449cf93 | Gianni Morandi - La Mia Nemica Amatissima [24-48][otto1961]
Added: 34eb25f1d6aea212474e75c5d1498bc7f449cf93 | Gianni Morandi - La Mia Nemica Amatissima [24-48][otto1961]
Added: a70da0f159f68e63299b564da2ccc2fb6ee070d4 | Planes.2013.BDRip.XviD.AC3.DUAL-REFLUX
Added: a70da0f159f68e63299b564da2ccc2fb6ee070d4 | Planes.2013.BDRip.XviD.AC3.DUAL-REFLUX
Added: 5a76df8b70d91b0967594cdbe3a756ea035c25ef | Boku dake ga Inai Machi
Added: fcbef34f7073522ad7cae6340e4a2e71d48202cd | Girlfriends.Day.2017.720p.WEBRip.DD2.0.x264-BDP[PRiME]
Added: b55f66971649dc16cfc8b455176a474e327a9ea5 | Россоловски Ленни - Ускоренное выздоровление (2014)
Added: 34eb2263bfaf6566614d8197812d2e7542bfb0e0 | Гражданин Никто. 2016.HDTVRip. [MGT_by_OVN]
Added: b55f66971649dc16cfc8b455176a474e327a9ea5 | Россоловски Ленни - Ускоренное выздоровление (2014)
Added: fcbef0d5983275e3e53fec9ab04586051463cae0 | Empire.3x02.HDitunes.www.DESCARGASMIX.com.avi
Added: 1c30dd0f711e39844fc2268ba0f0741a43b91a16 | Adobe Acrobat Reader DC v2015.020.20039 RePack by KpoJIuK
Added: 178ebf42d712803a665a05afc8ffc675566a280b | Adobe Photoshop CC 2014 (Mac)+Camera Raw 8.5 [ChingLiu]
Added: 8f89d2b0ae9f62bd4b20d4164223db58fc742043 | [ www.torrenting.com ] - Film.Independent.Spirit.Awards.2016.HDTV.x264-ALTEREGO
Added: 93b0a1413fa305f86c679a34c36d55a5d6806399 | Www.TamilRockers.cc-Kung Fu Panda 3 (2016) - [WEB-Rip-Tamil [Clear] - Mp3 - 400MB][KE].mkv
Added: 5977e6e30a2dca9298ee239d44e5e49e8933b66c | 2945-vesennij-klubnyak-dlya-tvoej-tachki
Added: 34eb25f1d6aea212474e75c5d1498bc7f449cf93 | Gianni Morandi - La Mia Nemica Amatissima [24-48][otto1961]
Added: 34eb25f1d6aea212474e75c5d1498bc7f449cf93 | Gianni Morandi - La Mia Nemica Amatissima [24-48][otto1961]
Added: 34eb25f1d6aea212474e75c5d1498bc7f449cf93 | Gianni Morandi - La Mia Nemica Amatissima [24-48][otto1961]
Added: 68c9e27d27bc1c366f2abdef3a2926dba43ceab0 | Fantastic Beasts and Where to Find Them 2016 BluRay x264-SINERS
Added: 1e018450d22cd3035f299a03e97735663215737c | Lightning - Bolts of Destruction (2003)(NK) DVDrip.AVI
Added: d80ffc8e6afb64bcd467ce1dfc6375540308480c | Melissa Mendiny - Guns - 209 HD images
Added: 2b23373861afbec1e5ce9b903e3e972df2e641c1 | Planetarium.2O17.D.WEB-DL.1O8Op.mkv
Added: 74204e24d3ccfe2ea85a2955883a31ad7900730f | YP-1TV-02x10-Spazz.mkv
Added: 74204e24d3ccfe2ea85a2955883a31ad7900730f | YP-1TV-02x10-Spazz.mkv
Added: 2b23373861afbec1e5ce9b903e3e972df2e641c1 | Planetarium.2O17.D.WEB-DL.1O8Op.mkv
Added: a3163bc87b8287ae26aab08f60228142984292fe | ملحق مجلس الاعيان (Mulhaq Majles Al-Ayaan) - Jordan
Added: a3163bc87b8287ae26aab08f60228142984292fe | ملحق مجلس الاعيان (Mulhaq Majles Al-Ayaan) - Jordan
Added: b71d4d8c2cc42946ab61207f98a30e52f2cb852b | Sound Radix - 32 Lives v2.0.5 OS X
Added: 34eb25f1d6aea212474e75c5d1498bc7f449cf93 | Gianni Morandi - La Mia Nemica Amatissima [24-48][otto1961]
Added: 34eb25397a007b549689f4149a5d35189c8c13f9 | Stormzone - Seven Sins (2015)
Added: b71d4d8c2cc42946ab61207f98a30e52f2cb852b | Sound Radix - 32 Lives v2.0.5 OS X
Added: 34eb25f1d6aea212474e75c5d1498bc7f449cf93 | Gianni Morandi - La Mia Nemica Amatissima [24-48][otto1961]
Added: b71d4d8c2cc42946ab61207f98a30e52f2cb852b | Sound Radix - 32 Lives v2.0.5 OS X
Added: 1da2d3d713939f99346a63787158134629462247 | Elegy.2008.PL.ENG.DVDRip.x264-0v0
Added: b71d4d8c2cc42946ab61207f98a30e52f2cb852b | Sound Radix - 32 Lives v2.0.5 OS X
```

**Comment by Raxvis** [comment]
Okay, so the issue is that add.js batches torrents.  Right now that batch size is 1000.  If you are only getting a couple right now, you can reduce your batched size on line 41 of add.js.

Move that to 1 or 5 right now, and then run it for a bit.   You should "Everything good with ES Update" in the logs if it has been added to ElasticSearch

**Comment by onigumo1990** [comment]
I set it to 1, and after 7 hours it finally got something, but it's an error:

```
UDP Server listening on 0.0.0.0:6881
Added: 909934f3eaf53162e3a9b9db78d52bd5b5a73501 | off_the_hook__20130703-128.mp3
Added: 909934f3eaf53162e3a9b9db78d52bd5b5a73501 | off_the_hook__20130703-128.mp3
{ Error: Request Timeout after 30000ms
    at /var/www/html/alphareign/scraper/node_modules/elasticsearch/src/lib/transport.js:336:15
    at Timeout._onTimeout (/var/www/html/alphareign/scraper/node_modules/elasticsearch/src/lib/transport.js:365:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  status: 408,
  displayName: 'RequestTimeout',
  message: 'Request Timeout after 30000ms' }
{ Error: Request Timeout after 30000ms
    at /var/www/html/alphareign/scraper/node_modules/elasticsearch/src/lib/transport.js:336:15
    at Timeout._onTimeout (/var/www/html/alphareign/scraper/node_modules/elasticsearch/src/lib/transport.js:365:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  status: 408,
  displayName: 'RequestTimeout',
  message: 'Request Timeout after 30000ms' }
```

**Comment by Raxvis** [comment]
Looks like ElasticSearch is down

**Comment by onigumo1990** [comment]
Actually, it's been up for slightly over a day according to service elasticsearch status:
```
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2017-03-04 19:17:06 CST; 1 day 3h ago
     Docs: http://www.elastic.co
  Process: 31317 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 31321 (java)
    Tasks: 60
   Memory: 182.4M
      CPU: 6min 17.655s
   CGroup: /system.slice/elasticsearch.service
           └─31321 /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-5.0.0.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch

Mar 04 19:17:06 ubuntu-services systemd[1]: Starting Elasticsearch...
Mar 04 19:17:06 ubuntu-services systemd[1]: Started Elasticsearch.
Mar 04 19:17:13 ubuntu-services elasticsearch[31321]: [2017-03-04T19:17:13,655][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/etc/elasticsearch/logging.yml], logging is configured via [/etc/elasticsearch/log4j2.properties]
```

**Comment by Raxvis** [comment]
So,  if you are timing out, it's generally because a) the service isn't
responding or b) it can't make the network connection to ES

**Comment by onigumo1990** [comment]
I went ahead and tried that URL you had me do last time, and funnily enough:
```
{"_index":"torrents","_type":"hash","_id":"909934f3eaf53162e3a9b9db78d52bd5b5a73501","_version":2,"found":true,"_source":{"name":"off_the_hook__20130703-128.mp3","search":"off the hook  20130703-128 mp3","infohash":"909934f3eaf53162e3a9b9db78d52bd5b5a73501","magnet":"magnet:?xt=urn:btih:909934f3eaf53162e3a9b9db78d52bd5b5a73501","updated":1488773382,"dht":1,"type":"","categories":[],"tags":[],"peers_updated":0}}
```

**Comment by Raxvis** [comment]
Oh good.  It's working!

**Comment by onigumo1990** [comment]
I guess so, now the webpage is saying: `Looks like we ran into an issue. Please try again later.` and I can't seem to find that line in any of the files. I'm going to try to track that line down

**Comment by Raxvis** [comment]
It's probably throwing and error and rendering an error page.  In
/index.php you can remove the error templates and should be able to see the
actual information.

**Comment by onigumo1990** [comment]
I'm sorry I'm not sure what you mean by error templates, I assumed you meant lines such as `$container['errorHandler'] = function ($c) {` and when I remove those lines that start like that that contain some sort of error handling I get `Slim Application Error` But it's not very descriptive and I will try to find out why it's causing an error

**Comment by onigumo1990** [comment]
I see what it is. I've put alphareign in a subdirectory since I run many websites and that's causing 404 errors (I should have realized sooner). I am going to try to tidy this up a bit somehow and I'll report back. Thanks a ton for your awesome help so far!

**Comment by Raxvis** [comment]
No problem.  Glad you found the problem!

**Comment by onigumo1990** [comment]
Some good news and bad news.

This is populating my add-out log: `Everything good with ES Update
Creation Times Added`

So that sounds good. I've set it up so that I call alphareign's folder as a subdomain so that the absolute paths work, but that same error on the page is showing up unfortunately. I am no longer getting bombarded with 404 errors, which I thought would solve the problem.

I'll be doing some more digging, just posting here in case you think of something before I do

**EDIT**: It looks like Slim is encountering issues, I'm looking into it currently. I don't know why it would be though. I know that composer downloaded slim in the vendor folder, but not quite sure what's going wrong at the moment

**Comment by JulesCornelissen** [comment]
Have you had any luck troubleshooting this? I'm currently at the same problem. Indexing and passing it along to ES is working fine, however I keep getting that same error page.

To try and avoid as many issues as possible I started on a clean Debian 8 install with just the bare essentials installed.

**Comment by Raxvis** [comment]
Try removing lines 66-94 in index.php and see what error you are getting.

Also, are you trying to install it as a root path or in a folder?  (exmple.com/ vs example.com/alphreign/)

**Comment by JulesCornelissen** [comment]
Thank you for the quick reply.

Sorry I haven't been able to respond earlier and won't be able to spend time on this for at least a couple of days, but I'll share some quick results. Commenting those lines shows that the error is caused by Slim, upon looking through the files I found a error/debug setting and turned it on. Turns out that Slim is throwing an error based on database access. I haven't had the time to troubleshoot this yet, but it should be configured fine.

I will try to report back when I have more results.

**Comment by Raxvis** [comment]
Can you paste the error here when you get a chance?

**Comment by JulesCornelissen** [comment]
The error I was getting is that it was unable to connect to the database, which was solved by install the php7.0-mysql package.
Following that I got an error which turned out to be that php7.0-mbstring was missing, so installed that too and now I'm getting a login screen! :D
Had some trouble as initially things weren't working on the login screen, however it turned out my rewrite engine wasn't working properly. Fixed that and so far so good, everything seems to be working!

Suggestion: add these two packages to the readme.md dependencies list next to the other php packages that are required.

I want to thank you for open sourcing this project, I think it's an awesome idea and I hope I'll be able to use it for a long time.

**Comment by Raxvis** [comment]
Glad to here you got things working!

I have added them to the README.md.

Closing this now since everything seems to be good to go.

**Comment by peva3** [comment]
I'm having this issue, and I installed the packages and it didn't fix it. Can you guys talk about what you did to fix slim?

I also am seeing this in the apache log

PHP Warning:  Missing argument 1 for Elasticsearch\\ClientBuilder::setHosts(), called in /var/www/html/middleware/es.php on line 6 and defined in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 314

**Comment by Raxvis** [comment]
Looks like the error is  you don't have a host defined for the ElasticSearch library.

What is your other error?
